title: "マクロ経済学備忘録"
summary: |-
  大学院で学んだマクロ経済学の備忘録です．

  講義のテキストは，
  David Romer, “Advanced Macroeconomics, 5th edition”, McGraw-Hill, 2018
  url: https://www.mheducation.com/highered/product/advanced-macroeconomics-romer/M9781260185218.html
  でした．
topics: []
published: false
price: 0
toc_depth: 2
chapters: []